<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-09T20:48:27 EET" name="Positive Login Test" finished-at="2024-03-09T20:48:31 EET" duration-ms="4004">
    <groups>
    </groups>
    <test started-at="2024-03-09T20:48:27 EET" name="Positive test" finished-at="2024-03-09T20:48:31 EET" duration-ms="4004">
      <class name="tests.PositiveTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method,java.lang.String,org.testng.ITestContext)[pri:0, instance:tests.PositiveTest@393671df]" started-at="2024-03-09T20:48:27 EET" name="setUp" finished-at="2024-03-09T20:48:28 EET" duration-ms="1265" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.PositiveTest.logInTest()]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@79e66b2f]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="logInTest()[pri:0, instance:tests.PositiveTest@393671df]" started-at="2024-03-09T20:48:28 EET" name="logInTest" finished-at="2024-03-09T20:48:31 EET" duration-ms="2587" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[actualSuccessMessage does not contain expectedSuccessMessage
expectedSuccessMessage: You logged into a secure are!
actualSuccessMessage: You logged into a secure area!
× expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: actualSuccessMessage does not contain expectedSuccessMessage
expectedSuccessMessage: You logged into a secure are!
actualSuccessMessage: You logged into a secure area!
× expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at tests.PositiveTest.logInTest(PositiveTest.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logInTest -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:tests.PositiveTest@393671df]" started-at="2024-03-09T20:48:31 EET" name="closeDriver" finished-at="2024-03-09T20:48:31 EET" duration-ms="123" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- tests.PositiveTest -->
    </test> <!-- Positive test -->
  </suite> <!-- Positive Login Test -->
</testng-results>
